services:
  identidock:
    image: ishikii/identidock-identidock:0.2
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    networks:
      - identidock-network
  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - identidock-network
  redis:
    image: redis
    networks:
      - identidock-network

networks:
  identidock-network:
    name: identidock-network
  