services:
  identidock:
    build: .
    ports:
      - "5000:9090"
    environment:
      ENV: PROD
    volumes:
      - ./app:/app
    networks:
      - identidock-network
  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - identidock-network
  redis:
    image: redis
    networks:
      - identidock-network

networks:
  identidock-network:
    name: identidock-network
  